remote_controller:
  type: joystick
  available_mode: all
front_sick:
  type: lidar
  available_mode: all
rear_sick:
  type: lidar
  available_mode: all
ublox:
  type: gps
  available_mode: all
xsens:
  type: imu
  available_mode: all
